### PR TITLE
added lightweight encoders 

### PR DESCRIPTION
**Pull request by florian-grond**
In this PR Thibaud Keller suggested to add some lightweight encoders as additional options for encoding HOA sources, also there are max re and in phase filters for the b-format up to order 5

### CODE REVIEW

**Comment by patrickdupuis** [comment]
@florian-grond please update your fork of sc3-plugins to bring it up to current master, and rebase you work on top of that. Only the last 2 commits are needed here. The CI for this repo was only added recently, so updating your fork will allow a proper CI run.

**Comment by florian-grond** [comment]
done


www.grond.at

**Comment by brianlheim** [comment]
The diff on this is still -8000 lines, is this PR meant to remove anything? The title and descriptions only say "add".

**Comment by patrickdupuis** [comment]
This PR should only include 2 commits: **added alternative encoders and optimizer** and **updated HOA Readme to refferece the new ugens**. 

You need to bring your fork of sc3-plugins up-to-date with the upstream repo, create a new local branch off of upstream/master, and apply your changes to that branch. That way, you're 100% certain that the PR you create from this branch against upstream/master will only include your additions, nothing else. 

There's a new contributing guide in the SC repo that explains the workflow for submitting PRs: https://github.com/supercollider/supercollider/blob/develop/CONTRIBUTING.md#pull-requests

**Comment by florian-grond** [comment]
I rebased on 3.10 now

**Comment by patrickdupuis** [comment]
No, this isn't right. There should only be 2 commits to this PR.

**Comment by florian-grond** [comment]
@patrickdupuis, sorry don't quite know how to proceed atm, might check in with you next week

**Comment by brianlheim** [comment]
this PR has multiple conflicts with master and still looks to be in bad shape. i'm closing as stale.

**Pull request closed without merging**
