### PR TITLE
Trailing commas in these two help files.

### PR DESCRIPTION
**Pull request by celesteh**
This breaks my entire help system, (which seems like also an important bug in the SCIDE)

### CODE REVIEW

**Comment by crucialfelix** [comment]
yeah, it's really fragile like that.

**Comment by snappizz** [comment]
Why is Travis failing?

**Comment by snappizz** [comment]
SCDoc shouldn't fail entirely when presented with just one or two malformed help files. In fact, I'm not seeing this behavior -- errors are displayed but it still successfully indexes everything else:

    SCDoc: Indexing help-files...
    ERROR: In /home/nathan/.local/share/SuperCollider/Extensions/sc3-plugins-sc/JoshUGens/sc/HelpSource/Classes/PV_PlayBuf.schelp:
      At line 5: syntax error, unexpected newline, expecting text or URL

    ERROR: In /home/nathan/.local/share/SuperCollider/Extensions/sc3-plugins-sc/JoshUGens/sc/HelpSource/Classes/PV_RecordBuf.schelp:
      At line 5: syntax error, unexpected newline, expecting text or URL

    SCDoc: Indexed 2503 documents in 1.42 seconds

**Comment by celesteh** [comment]
It turns out it was failing for some unrelated reason that has since mysteriously fixed itself....

**Pull request merged**
