### PR TITLE
Update README to reflect frozen status

### PR DESCRIPTION
**Pull request by snappizz**
see discussion at https://www.listarc.bham.ac.uk/lists/sc-dev/msg58832.html for background.

### CODE REVIEW

**Comment by LFSaw** [comment]
Interesting idea, although IMHO this PR seems to be a little too far ahead of discussion. However, since discussion on sc-dev seems to have stalled, I'll try to open it up again here.

I put my thoughts about this into this email to sc-dev: https://www.listarc.bham.ac.uk/lists/sc-dev/msg58854.html

I can condense this down into several questions:

+ When using the cookiecutter plugin develop environment, how do I ensure my plugins to be seen/browsed by the community?
+ How Do I move my existing plugins out of sc3-plugins without breaking people's workflow (duplicate plugins installed etc.)?
+ How do I easily install/deinstall plugins not in this repository?

**Comment by patrickdupuis** [comment]
@LFSaw the conversation has indeed stalled. Would you mind re-igniting it with the questions you've posted above?

**Comment by LFSaw** [comment]
> Would you mind re-igniting it with the questions you've posted above?

done. :)

**Comment by mtmccrea** [comment]
I agree this is a bit ahead of discussion and the proposal needs to have, at a minimum a documented "preferred" way to authors to produce UGens ready for install from their own repos (i.e. a release procedure, not just how to make a UGen), and for users to download and install UGens from out in the wild.

**Comment by telephon** [comment]
>When using the cookiecutter plugin develop environment, how do I ensure my plugins to be seen/browsed by the community?

I suppose that UGens would be listed as part of the quarks directory file, wouldn't they?

>How Do I move my existing plugins out of sc3-plugins without breaking people's workflow (duplicate plugins installed etc.)?

This is unsolved so far.

**Comment by LFSaw** [comment]
fyi I'll refrain from taking part in this discussion. Reasons here:

https://github.com/supercollider/incubator/issues/1

**Pull request closed without merging**
