### PR TITLE
readme: fix build instructions

### PR DESCRIPTION
**Pull request by brianlheim**
also recommend building supernova plugins

https://github.com/supercollider/supercollider/issues/5159#issuecomment-690243648

### CODE REVIEW

**Comment by redFrik** [comment]
shouldn't you also mention that you also fixed Release mode build here?  and warn about that any build prior (unsure for how long) might have been Debug?

**Comment by brianlheim** [comment]
no, we don't normally provide that level of detail in build instructions, and this would be a bad place to make that kind of announcement. however, i can let people know on the mailing list and forum.

**Comment by redFrik** [comment]
no, not in the instructions themselves - i meant here on github or in the git commit message.  the title "fix build instructions" is very vague and there wasn't a single mention of the (IMO) much bigger issue that you corrected - the debug vs release mode build.
yes please, some form of announcement on the mailing list would be good.

**Comment by brianlheim** [comment]
uhh, okay. i've sent out the announcement. changelog for the next release will include this PR.

**Comment by redFrik** [comment]
great. thanks!

**Comment by brianlheim** [comment]
also added to the release info here: https://github.com/supercollider/sc3-plugins/releases/tag/Version-3.11.0. that page is linked from `supercollider.github.io/sc3-plugins` too.

**Pull request merged**
