### PR TITLE
Build plugins for supernova if we built it

### PR DESCRIPTION
**Pull request by vivid-synth**
We should at least be building plugins for supernova when we're building it in the SC repo

### CODE REVIEW

**Comment by danstowell** [comment]
I don't object - but I'd just point out that this is effectively "guessing" that supernova is available/wanted. (Your comment says "if we built it" or "when we're building it" but that's not actually tested for.)

**Comment by vivid-synth** [comment]
@danstowell true, but it's the same cmake test we use for building supernova by default. I'd be all for compiling it all the time (or anytime supernova is installed) if that's possible, but I at least don't want to be building supernova by default but with no ugens to use it with.

**Comment by danstowell** [comment]
"no ugens" isn't strictly true now is it? but np, go ahead

**Comment by vivid-synth** [comment]
@danstowell -- oh, very true: you mean the ones from the SC repo, right?

Also, I've only done the flag this way because of my limited knowledge of cmake: is there a way to say "if supernova is installed"?

**Comment by danstowell** [comment]
Well you could check for the existence of the executable `supernova` in the path, but meh, that feels a bit flakey too. (Supernova doesn't install headers of its own; if it did, I'd say "check for those")

**Comment by bagong** [comment]
No prob for Windows.

**Pull request merged**
