### PR TITLE
Compatibility with BSD systems

### PR DESCRIPTION
**Pull request by yurivict**
* CMAKE_SYSTEM_NAME match
* Use of ${CMAKE_DL_LIBS}

### CODE REVIEW

**Comment by yurivict** [comment]
You're welcome!

(Upstreaming the patch from the FreeBSD port.)

**Comment by patrickdupuis** [comment]
@yurivict looks like cmake is failing. @brianlheim suggested over on slack that `“${CMAKE_DL_LIBS}”` (writen in quotes) may be the solution.

**Comment by yurivict** [comment]
>  looks like cmake is failing

Hmm, it doesn't fail for me.
You can also see examples of use in other projects in the same way: 
https://github.com/awesomeWM/awesome/issues/82
https://gitlab.maisondelasimulation.fr/l2c/l2c/commit/b2f3e12c7050f19a3cf591e8cfe925b67115bfbe

**Comment by brianlheim** [comment]
> Hmm, it doesn't fail for me.

That's great but we're talking about our CI

**Comment by brianlheim** [comment]
Fantastic, thank you!

**Pull request merged**
