### PR TITLE
Make LadspaUGen optional

### LINKED ISSUE #259: Cmake option to disable LadspaUGen
LadspaUGen is known to prevent the server from booting in some Linux environments. See #257 (erroneously closed because of a misdiagnosis -- continued at https://github.com/supercollider/supercollider/issues/4421 where it turned out to be an sc3-plugins issue after all).

LadspaUGen hasn't been maintained in several years. See #23 (4.5 years old, unfixed) and #210 (9/2018).

If it isn't going to be fixed (and I have no confidence that it will be), then we should provide a way for users to turn it off.

### PR DESCRIPTION
**Pull request by gusano**
Fixes #259

### CODE REVIEW

**Comment by patrickdupuis** [comment]
I get this error when trying to run `cmake -DLADSPA=OFF ..`

```
CMake Error at source/CMakeLists.txt:363 (install):
  install TARGETS given target "ladspalist" which does not exist in this
  directory.
```

**Comment by gusano** [comment]
@patrickdupuis doh.. I fixed it and force pushed.. sorry for that and thanks for spotting

**Comment by patrickdupuis** [comment]
Thanks! Tested on Linux.

**Comment by brianlheim** [comment]
There should be more documentation than this -- maybe a known issues section in the readme?

**Comment by gusano** [comment]
@brianlheim note added in the readme

**Comment by totalgee** [comment]
This frequent source of confusion ("why does scsynth fail to boot on my Linux distro?") came up again in the TidalCycles forums recently:
https://club.tidalcycles.org/t/supercollider-wont-boot/2285

The "solution" of deleting the LADSPA plugin locally was discussed, and I sent a link to this PR. The comment was made that hopefully it would be merged soon... ;-)

**Review by brianlheim — APPROVED** [review]

**Comment by totalgee** [comment]
Thanks @brianlheim !

**Pull request merged**
