### PR TITLE
set flags for sse

### PR DESCRIPTION
**Pull request by sonoro1234**
They were not setted.
This was discovered in a denormal numbers issue #59
@timblechmann I copied flags from supercollider but I am not sure why -mfpmath=sse is disabled in apple if compiler is not clang
```
+    if(NOT APPLE AND NOT CMAKE_COMPILER_IS_CLANG)
+        set(CMAKE_C_FLAGS "${CMAKE_C_FLAGS} -mfpmath=sse")
+        set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -mfpmath=sse")
+    endif()
```

### CODE REVIEW

**Comment by sonoro1234** [comment]
@timblechmann Ping?

**Comment by timblechmann** [comment]
i don't think there are any 32bit x86 cpus without sse unit. we're speaking about roughly 20 years old intel  deskop cpus and some weird x86 cpus for embedded machines, which won't have sse

**Comment by sonoro1234** [comment]
So, the lines above, copied from CMakeList.txt in supercollider, are ok or not?

**Comment by LFSaw** [comment]
I'd say go for inclusion. We follow the supercollider build process as a guideline in sc-users. the question of why  ```-mfpmath=sse``` is disabled in apple if compiler is not ```clang``` might be forwarded to the supercollider development issue tracker. A possible change there should be mirrored in ```sc-plugins```.

**Comment by timblechmann** [comment]
googling for "clang mfpmath" gives me as the first hit: https://stackoverflow.com/questions/19600238/how-do-i-pass-mfpmath-sse-to-llvm-using-clang

the first answer is:
> You do not need this flag with clang. It defaults to "-mfpmath=sse" as soon as your processor does ? support it.

before asking a human, it might sometimes be faster to ask a computer

**Comment by LFSaw** [comment]
Thanks for looking into this, @timblechmann
. So we can safely merge?

**Comment by LFSaw** [comment]
thanks :)

**Pull request merged**
