### PR TITLE
converting html help to SCDoc format

### PR DESCRIPTION
**Pull request by dotinspace**
Converted more files from html to scdoc, removed old html files, and removed unneeded categories.

### CODE REVIEW

**Comment by crucialfelix** [comment]
I'm in favor of keeping the `UGens>Analysis:Synthesis` tag. That would make them more discoverable.

Otherwise looks great and ready to merge

**Comment by dotinspace** [comment]
Aha, I thought I'd remove that category, since these UGens are not part of the base SC installation. Done! A bit unsure about proper categories to add to these UGens: `Balance` (Multichannel?), `OverlapTexture`, `WarpOverlap`, `WarpZ`, `Metro`, `ProcEvents`, `ProcMod`, `ProcModR`.

**Comment by crucialfelix** [comment]
From a user perspective I would like to see all Analysis UGens that I have installed. Maybe I'm working on a problem and I want to look through the docs for inspiration. That's my personal 2c.

**Comment by snappizz** [comment]
52/71

**Pull request merged**
