### PR TITLE
atk: avoid branches in inner loop and memory hazards

### PR DESCRIPTION
**Pull request by timblechmann**
branches and memory are MUCH slower than doing the actual computation.
this patch speeds roughly doubles the performance of atk panners

### CODE REVIEW

**Comment by joshpar** [comment]
Hi Tim,
The patch looks fine, but it will drastically increase the number of multiplies needed to calculate most of the matrices. Have you tested it along with the transforms as well?
Otherwise, looks fine to me.
Best
Josh

/*
Josh Parmenter
www.realizedsound.net/josh
*/

**Comment by timblechmann** [comment]
it might drastically increase the number of multiplies, but also drastically reduces the number of branches, which have a much bigger impact on performance.

**Comment by joshpar** [comment]
Go for it

/*
Josh Parmenter
www.realizedsound.net/josh
*/

**Comment by telephon** [comment]
>Go for it

Josh, can you merge it?

**Comment by bagong** [comment]
I breaks the Mac build at the same place where it happened before Scott C added a workaround.

**Comment by bagong** [comment]
Ah, while the build broke, that was obviously due to the current clang version when I tested the build, which must have differed from Scott C's the one specified in Scott's workaround (6.0.0.600005) for the vectorization problem. So there is no connection to this PR.
The good news: the clang bug is gone in v. 6.1!
So no build-prob because of this PR!! Sorry for the misinterpretation.

**Comment by bagong** [comment]
>> Go for it

> Josh, can you merge it?

@joshpar, I don't think anybody will merge it except you ;)

**Comment by joslloand** [comment]
Hi All,

I can merge... I'd be ready to merge the request, but I'm seeing:

>Merge with caution!
>Failed — The Travis CI build failed

As a result, I'm hesitant to push go. Any advice here?

**Comment by bagong** [comment]
The build error is not related to the PR. It was because of the compiler version used by travis at the time the PR was submitted. I just retriggered the build and it works fine.

**Comment by joslloand** [comment]
Merged...

**Pull request merged**
