### PR TITLE
additional lightweight HOAUgens

### PR DESCRIPTION
**Pull request by thibaudk**
Hello,

this PR is supposed to solve the issues of #207.
After a few back and forth, I do think that these additions have their interest,
and the build time is not that much longer than with the HOAUgens at the moment.
I may look into a jumble build next, hoping to reduce the number of targets...

tested on Ubuntu 20.04
and supercollider 3.11

### CODE REVIEW

**Comment by dyfer** [comment]
Hello @thibaudk 
Thank you for your PR and sorry for not attending to this earlier.
That's quite a number of new UGens! From previous discussions on HOAUgens, it seemed that the general direction was to possibly move them all outside of sc3-plugins, rather than adding more to them to this repository. How do you feel about this addition @telephon @patrickdupuis @joshpar ?

**Comment by thibaudk** [comment]
Hi @dyfer,

Actually, The HOAUgens are largely based on @sekisushai 's [ambitools](https://github.com/sekisushai/ambitools) that was recently relocated and updated. The new dsp's can be found [here](http://sekisushai.net/git/sekisushai/ambitools/src/branch/master/faust).

I should look into re-basing HOAUgens and @florian-grond 's [SC-HOA](https://github.com/florian-grond/SC-HOA) on this new version that seem to amount to less plugins.

**Comment by thibaudk** [comment]
Hi, very sorry, I have not touched it since. So I suppose you can consider the PR stale at this point.
The files were generated with Faust 2.18.0 against the SuperCollider version at the time. The current Faust is 2.74.6, so it may be a little outdated.

**Comment by dyfer** [comment]
I feel that we shouldn't be pulling in that many plugins into sc3-plugins - it should be its own plugin suite. As this is stale, I suggest closing this.

**Comment by capital-G** [comment]
Then let's close it - reopen if I necessary.

**Pull request closed without merging**
