### PR TITLE
Merge pull request #213 from mtmccrea/topic/add-quantityugens

### PR DESCRIPTION
**Pull request by mtmccrea**
Cherry-pick #213 into `3.10`.

### CODE REVIEW

**Comment by snappizz** [comment]
sorry, but the 3.10 branch is only for bug fixes in 3.10.x, and no new features should be merged into it at this point.

**Comment by mtmccrea** [comment]
Thanks for your response @snappizz. Would you mind answering a couple questions about the merge process?

1. Is the responsibility of the author of the original author of the PR to `develop` to also cherry pick and submit a PR into a release branch?
2. Do changes wait in `develop` for further testing, or to wait for the appropriate time in the release cycle? (e.g. this shouldn't be merged yet because, as it's a new feature, it needs to wait for `3.11`.)
3. Is there a rough time estimate on when versions increment? Should we expect new features, even if vetted in `develop` take a number of months to be in a release?

I've checked both the `CONTRIBUTING.md` and [git-workflow-and-guidelines](https://github.com/supercollider/supercollider/wiki/git-workflow-and-guidelines) and asked about this on [another thread](https://github.com/supercollider/supercollider/pull/4082#issuecomment-451632496) and haven't come to a clear understanding.

Thanks!

**Comment by snappizz** [comment]
hi mike, first off i'm sorry for any frustrations about the state of the project docs -- often it's incomplete or somewhat behind the actual process we tend to do. also sorry for not being responsive on your Plotter PRs, will take a look in a moment.

thank you for being inquisitive about this, here are my answers to your questions:

1. as someone who contributes pull requests, you don't necessarily need to do the cherrypicking -- i'm responsible for it as release manager, and patrick and brian will often step up. but as you've already seen, i take breaks sometimes, miss things, etc. if you think something should be cherrypicked but hasn't, you're free to ping me. if you step up and do it yourself that's also okay.
2. the `develop` branch waits until the next 3.x release. this gives us a grace period to ensure stability of features. often we've merged new features into `develop` and discovered issues with them before they were officially released.
3. ideally i aim for 3-4 months but usually it extends to 6+. the timing of 3.x release is dependent on the amount of work that gets done -- at least one big new feature per 3.x release. if the releases are too quick then it's overwhelming for users, if they're too slow then we lose development momentum.

in the particular case of sc3-plugins, the plugin release cycle of 3.x versions is strictly simultaneous with that of core supercollider versions. the reasons are not because of any development cycle of sc3-plugins, but because it's confusing for users if they're out of sync. it's easiest to simply declare that 3.10 supercollider works with 3.10 plugins, and so forth.

if the sc3-plugins release cycle is too slow for your needs, there is a better alternative: use [brian's cookiecutter repo](https://github.com/supercollider/cookiecutter-supercollider-plugin/), which automatically packages your plugins for windows, linux, and macos.

**Comment by mtmccrea** [comment]
Thanks for clarifying this, Nathan. I hope I didn't come across as frustrated, just looking for clarity on the workflow and I didn't want to overstep by trying to merge out of turn. I totally understand the speed of development fluctuates with everyone's availability, I go on and off the radar myself...

I'm trying to step up my efforts in contributing so this will be helpful going forward. I work in a fairly tight loop with some people at the university where I work and when we create fixes or additions it can be tough to keep track of what is still in our private builds and what has made it into the distribution for others to access.

Thanks for the reminding me of the cookie cutter repo, I've been meaning to try that. I've been getting along well with your `example-plugins` workflow, so thanks for that :-). As an aside: is there a straightforward way to build an xcode project from the example-plugin template? That would be great.

So for the sake of this pr, should I go ahead and close it and wait until a `3.11` branch to do it again?

Thanks again.

**Comment by snappizz** [comment]
thanks for your understanding, and glad to see that this helped! if you have suggestions for how we can improve our project documentation i welcome any feedback.

> So for the sake of this pr, should I go ahead and close it and wait until a `3.11` branch to do it again?

no need to do so -- `master` *is* 3.11. at some point we will go into release mode for 3.11 by creating a `3.11` branch off `master`, and that branch will automatically have #213 embedded in it, so nothing is required from your end.

> As an aside: is there a straightforward way to build an xcode project from the example-plugin template? That would be great.

unfortunately i'm not a macOS user, so i'll have to defer to others on how to do that -- if you find a solution feel free to document it.

**Comment by mtmccrea** [comment]
> no need to do so -- `master` _is_ 3.11
Ah, of course, I forgot that there isn't `develop` on `sc3-plugins`! 

>if you find a solution feel free to document it.
Definitely will if I come up with a solution!

**Comment by brianlheim** [comment]
> is there a straightforward way to build an xcode project from the example-plugin template? That would be great

Yes; CMake has an XCode project generator.

**Comment by snappizz** [comment]
closing per discussion

**Pull request closed without merging**
