### PR TITLE
BerlachUGens: get oversampling ugens working for blocksize > 64

### LINKED ISSUE #9: [berlach] Oversampling ugens crash server when using block sizes larger than 64

### PR DESCRIPTION
**Pull request by snappizz**
Fix #9. Turns out it's not so bad.

### CODE REVIEW

**Comment by telephon** [comment]
looks good, but maybe someone who uses them could test

**Comment by snappizz** [comment]
yeah, i didn't test this very thoroughly.

**Comment by snappizz** [comment]
I just realized I forgot to change `DefineSimpleUnit` to `DefineDtorUnit`!

**Comment by snappizz** [comment]
Okay, that fixes it. Here is a test case:

    (
    {
        var classes;
        classes = [OSWrap4, OSWrap8, OSTrunc4, OSTrunc8, OSFold4, OSFold8, Clipper8, Clipper4, SoftClipper8, SoftClipper4, SoftClipAmp8, SoftClipAmp4];
        classes.collect(_.ar(SinOsc.ar, -0.8, 0.8));
    }.plot(0.01);
    )

**Comment by bagong** [comment]
Fine on Windows! Thanks!

**Pull request merged**
