### PR TITLE
59837f4 need C++11 to build std::trunc from 7a82fdb

### PR DESCRIPTION
**Pull request by andersvi**

### CODE REVIEW

**Comment by bagong** [comment]
Any reasons not to commit this?

**Comment by telephon** [comment]
I can't see any

**Comment by bagong** [comment]
Then why don't you press the button? :)

**Comment by telephon** [comment]
just because i am potentially blind

**Comment by bagong** [comment]
Hahaha, I don't think so, and there is always revert ;) Saved me typing -DCPP11=ON about 10 times today ;) (and trying to remember if it's c++11 or cpp11... Thanks!

**Pull request merged**
