### PR TITLE
Update STK from 4.4.2 to 4.4.4

### PR DESCRIPTION
**Pull request by danstowell**
See issue #44. I've gone for version 4.4.4 (not 4.5.0) since that's a minor API change and also matches current debian.

I've tested that it builds OK but not that it works, since I'm not an STK user.

### CODE REVIEW

**Comment by danstowell** [comment]
Merging this since it's a minor versionbump and the "new" Stk wrapper is also there too

**Comment by telephon** [comment]
on cmake, I get the following error:

```
CMake Error at source/StkInst/CMakeLists.txt:22 (list):
  list sub-command REMOVE_ITEM requires two or more arguments.
```

**Comment by danstowell** [comment]
@telephon that's not an issue with this PR. It's caused by #47, simply because you need to run `git submodule init` since #47 adds a new submodule. (NB: I believe the obscure error message that you quote is already fixed, replaced with an informative one...) Please add a comment on #47 if the problem persists for you.

**Comment by telephon** [comment]
ah good - this fixed it.

**Pull request merged**
