### PR TITLE
website updates

### PR DESCRIPTION
**Pull request by dyfer**
After recent updates there seemed to be problems with building our website, see https://github.com/supercollider/sc3-plugins/settings/pages

The commit updating the source of the cayman theme seems to solve it. I've also updated jekyll etc since we had a [security alert about kramdown](https://github.com/supercollider/sc3-plugins/security/dependabot/Gemfile.lock/kramdown/open).

I'm new to maintaining gh pages, let me know if any of this needs changing.

### CODE REVIEW

**Comment by joslloand** [comment]
@dyfer, it might be worth updating to the latest version of [gh-pages](https://github.com/github/pages-gem/releases). At the moment, this is [v216](https://github.com/github/pages-gem/releases/tag/v216).

The dependencies for this version are [listed here](https://pages.github.com/versions/).

**Comment by dyfer** [comment]
> @dyfer, it might be worth updating to the latest version of [gh-pages](https://github.com/github/pages-gem/releases). At the moment, this is [v216](https://github.com/github/pages-gem/releases/tag/v216).

I think I'm doing that, isn't that so? https://github.com/supercollider/sc3-plugins/pull/318/files#diff-89cade48462044ee1b672dc5f4c3ec250fbd29effcd8932096a23c1283c6731fR49

**Comment by joslloand** [comment]
> I think I'm doing that, isn't that so? https://github.com/supercollider/sc3-plugins/pull/318/files#diff-89cade48462044ee1b672dc5f4c3ec250fbd29effcd8932096a23c1283c6731fR49

Doh! Yep!! I didn't actually look!!

MY BAD!!!

**Comment by dyfer** [comment]
> This should do the trick.

Should we merge then and see if it works?

**Comment by joshpar** [comment]
@dyfer - I think so.. hold on to your butts.

**Review by joshpar — APPROVED** [review]
let's try it!

**Comment by dyfer** [comment]
OK, it seems to have worked fine.

**Comment by joslloand** [comment]
Hurrah!

**Pull request merged**
