### PR TITLE
Add option for LIB_SUFFIX

### PR DESCRIPTION
**Pull request by tdug**
https://github.com/supercollider/sc3-plugins/issues/309

Allow option to add `LIB_SUFFIX` to cmake.

### CODE REVIEW

**Comment by tdug** [comment]
Related: https://github.com/supercollider/supercollider/pull/5644

**Review by dyfer — CHANGES_REQUESTED** [review]
Thanks!
This looks good functionally, I have one request: in this file we generally have 4-space indentation, would you mind to adjust your edit to also use 4 spaces?

**Comment by dyfer** [comment]
Also, if you wish, feel free to add a note about this in the [README](https://github.com/supercollider/sc3-plugins#cmake-options)

**Review by dyfer — APPROVED** [review]
Thanks!

**Pull request merged**
